-- Crear tabla CATEGORIAS
CREATE TABLE CATEGORIAS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- Crear tabla PRODUCTOS
CREATE TABLE PRODUCTOS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(1000),
    precio DECIMAL(10, 2) NOT NULL,
    peso DECIMAL(10, 3),
    altura DECIMAL(10, 2),
    anchura DECIMAL(10, 2),
    profundidad DECIMAL(10, 2),
    fecha_creacion TIMESTAMP NOT NULL,
    categoria_id BIGINT,
    CONSTRAINT fk_categoria FOREIGN KEY (categoria_id) REFERENCES CATEGORIAS(id)
);

-- Insertar datos de prueba en CATEGORIAS
INSERT INTO CATEGORIAS(nombre) VALUES ('Electrónica');
INSERT INTO CATEGORIAS(nombre) VALUES ('Ropa');
INSERT INTO CATEGORIAS(nombre) VALUES ('Hogar');

-- Insertar datos de prueba en PRODUCTOS
INSERT INTO PRODUCTOS(
    nombre, descripcion, precio, peso, altura, anchura, profundidad, fecha_creacion, categoria_id
) VALUES (
    'Televisor 55"', 'Televisor LED 4K', 799.99, 12.5, 70.0, 120.0, 10.0, CURRENT_TIMESTAMP, 1
);

INSERT INTO PRODUCTOS(
    nombre, descripcion, precio, peso, altura, anchura, profundidad, fecha_creacion, categoria_id
) VALUES (
    'Camiseta', 'Camiseta de algodón talla M', 19.99, 0.2, 0.5, 30.0, 0.2, CURRENT_TIMESTAMP, 2
);

INSERT INTO PRODUCTOS(
    nombre, descripcion, precio, peso, altura, anchura, profundidad, fecha_creacion, categoria_id
) VALUES (
    'Sofá 3 plazas', 'Sofá de cuero color negro', 499.99, 45.0, 90.0, 200.0, 85.0, CURRENT_TIMESTAMP, 3
);

CREATE TABLE USUARIOS (
    -- Clave Primaria
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    password VARCHAR(72) NOT NULL,
    role VARCHAR(100) NOT NULL
);

INSERT INTO USUARIOS (id, firstname, lastname, email, password, role ) VALUES 
(1,'user', 'user', 'user@a.com', '$2a$12$PB6GwcJCu44g/T895VObduyyMGsX.Rl/QN0kU/IY0l9HOPokGJBpe', 'USER'),
(2,'admin', 'admin', 'admin@a.com', '$2a$12$crH/Tuxn/3in7inhgLzoiOTfaXm2sLQy5alm0pwlBXu2z./MzwTMW', 'ADMIN');

