-- Crear tabla CATEGORIAS
DROP TABLE IF EXISTS CATEGORIAS;
DROP TABLE IF EXISTS PRODUCTOS;

CREATE TABLE IF NOT EXISTS CATEGORIAS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- Crear tabla PRODUCTOS
CREATE TABLE PRODUCTOS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(1000),
    precio DECIMAL(10, 2) NOT NULL,
    peso DECIMAL(10, 3),
    altura DECIMAL(10, 2),
    anchura DECIMAL(10, 2),
    profundidad DECIMAL(10, 2),
    fecha_creacion TIMESTAMP NOT NULL,
    categoria_id BIGINT,
    CONSTRAINT fk_categoria FOREIGN KEY (categoria_id) REFERENCES CATEGORIAS(id)
);

-- Insertar datos de prueba en CATEGORIAS
INSERT INTO CATEGORIAS(nombre) VALUES ('Electrónica');
INSERT INTO CATEGORIAS(nombre) VALUES ('Ropa');
INSERT INTO CATEGORIAS(nombre) VALUES ('Hogar');

-- Insertar datos de prueba en PRODUCTOS
INSERT INTO PRODUCTOS(
    nombre, descripcion, precio, peso, altura, anchura, profundidad, fecha_creacion, categoria_id
) VALUES (
    'Televisor 55"', 'Televisor LED 4K', 799.99, 12.5, 70.0, 120.0, 10.0, CURRENT_TIMESTAMP, 1
);

INSERT INTO PRODUCTOS(
    nombre, descripcion, precio, peso, altura, anchura, profundidad, fecha_creacion, categoria_id
) VALUES (
    'Camiseta', 'Camiseta de algodón talla M', 19.99, 0.2, 0.5, 30.0, 0.2, CURRENT_TIMESTAMP, 2
);

INSERT INTO PRODUCTOS(
    nombre, descripcion, precio, peso, altura, anchura, profundidad, fecha_creacion, categoria_id
) VALUES (
    'Sofá 3 plazas', 'Sofá de cuero color negro', 499.99, 45.0, 90.0, 200.0, 85.0, CURRENT_TIMESTAMP, 3
);
